name: Test License Data
on:
  push:
    branches:
      - develop
defaults:
  run:
    shell: bash
jobs:
  test-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test license download
        id: test-fetch
        working-directory: 'test'
        run: |
          test_file="fetch_license.sh"
          if [[ ! -f "$test_file" ]]; then
            echo "::error::Missing test file test/$test_file"
            exit 1
          fi
          ./"$test_file"
      - name: Test license headers against reference
        id: test-headers
        working-directory: 'test'
        run: |
          test_file="license_headers_match.pl"
          test_dep="YAML-Tiny/lib/YAML/Tiny.pm"
          if [[ ! -f "$test_file" ]]; then
            echo "::error::Missing test file test/$test_file"
            exit 1
          fi
          if [[ ! -f ../tools/"$test_dep" ]]; then
            echo "::error::Missing test dependency tools/$test_dep"
            exit 1
          fi
          ./"$test_file" ../licenses/package.yml
